---
abstract: "detect MooseX::Declare's 'class' keyword in files."
author:
  - 'Ash Berlin C<< <ash@cpan.org> >>. (C) 2009. All rights reserved.'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Differences: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.97'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Class::Discover
name: Class-Discover
no_index:
  directory:
    - inc
    - t
requires:
  ExtUtils::MM_Unix: 0
  File::Find::Rule: 0
  File::Find::Rule::Perl: 1.07
  File::Temp: 0
  PPI: 0
  Path::Class: 0
  Test::Differences: 0
  Test::More: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.000003
